---

- name: "Build hosts file"
  become: yes
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ fqdn }}$"
    line: "127.0.1.1 {{ fqdn }}"
    state: present

- name: Set Hostname with hostname command
  become: yes
  hostname: name="{{ fqdn }}"

- name: update apt cache
  apt:
    update_cache: yes
  become: yes

- name: install ssl system requirements
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: ssl_requirements
  tags:
    - packages

- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: system_packages
  tags:
    - packages

- command: cp /usr/share/graphite-web/graphite.wsgi /usr/lib/python2.7/dist-packages/graphite/graphite_web.py
  args:
    creates: "/usr/lib/python2.7/dist-packages/graphite/graphite_web.py"
  become: true

- include_tasks: carbon.yml

- include_tasks: systemd.yml
  tags:
    - systemd

- include_tasks: postgresql.yml
  tags:
    - postgresql

- name: ensure graphite is running
  become: true
  service:
    name: graphite
    state: restarted
    enabled: yes
